### ISSUE TITLE
Discussion question - collaboration

### ISSUE THREAD

**Issue by RichardScottOZ** [brazil-data-cube/code-gallery#14]
Hi all,

Who would we talk to about collaboration, data access, etc.?

e.g. https://www.ozminerals.com/operations/pedra-branca/

**Comment by gqueiroz** [comment]
> Hi all,
> 
> Who would we talk to about collaboration, data access, etc.?
> 
> e.g. https://www.ozminerals.com/operations/pedra-branca/

Hi @RichardScottOZ , please, you can reach the coordinators of the project at brazildatacube@inpe.br.

**Comment by RichardScottOZ** [comment]
Thanks - anyone in particular?  I hadn't heard back.

**Comment by gqueiroz** [comment]
Apologize, could resend the e-mail and add me in copy?

**Comment by RichardScottOZ** [comment]
Used other options.
